#!/usr/bin/env ruby

require 'net/http'

image_dir = '/tmp/gt'
puts "Deleting #{image_dir}"
`rm -rf #{image_dir}`

puts 'Fetching list of Glamorous Toolkit releases...'
host = 'dl.feenk.com'
base_url = "https://#{host}/gt/"
release_listing = Net::HTTP.get_response(URI.parse(base_url)).body

re = /href="(GlamorousToolkit-Linux-x86_64-v(.*?)\.zip)"/

matches = release_listing.scan re
latest_zip = matches.collect { |m| m[0] }.sort.reverse.first

write_location = "/tmp/#{latest_zip}"

if File.exist? write_location
  puts "Deleting previous #{write_location} file"
  File.delete write_location
end

url = "#{base_url}#{latest_zip}"
`curl -L #{url} -o #{write_location}`

puts "Unarchiving GT to #{image_dir}"
`unzip #{write_location} -d #{image_dir}`

puts '✅ All done!'
