#!/usr/bin/env bash

set -eu

/tmp/gt/bin/GlamorousToolkit-cli /tmp/gt/GlamorousToolkit.image eval --save "Smalltalk globals at: #BaselineOfDgAoc2023 ifAbsent: [ Metacello new repository: 'https://github.com/semperos/aoc2023'; baseline: 'DgAoc2023'; load. Smalltalk saveSession ]. "
