#!/usr/bin/env bash

set -eu

/tmp/gt/bin/GlamorousToolkit-cli /tmp/gt/GlamorousToolkit.image eval --save "Smalltalk globals at: #BaselineOfDgAoc2023 ifAbsent: [ Metacello new repository: 'github://semperos/aoc2023:main/src'; baseline: 'DgAoc2023'; load. Smalltalk saveSession ]. "
